# Generated by Django 5.2.8 on 2025-11-17 19:18

import nanoid_field.fields
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('training_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
