# Generated by Django 5.2.8 on 2025-12-01 19:38

import django.db.models.deletion
import nanoid_field.fields
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sir_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'training_group',
            },
        ),
        migrations.CreateModel(
            name='TrainingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('training_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
            options={
                'db_table': 'training_time',
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('FA', 'First Aid'), ('RE', 'Rescue ability'), ('LI', 'Lifeguard'), ('CL', 'C-Training license'), ('BL', 'B-Training license'), ('AL', 'A-Training license')], max_length=2)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.person')),
            ],
        ),
    ]
