# Generated by Django 5.2.12 on 2026-04-11 10:55

import django.db.models.deletion
import nanoid_field.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('role', models.CharField(choices=[('S', 'Swimmer'), ('A', 'Trainer Assistant'), ('T', 'Trainer'), ('X', 'Admin')], default='S', max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            options={
                'db_table': 'person',
                'ordering': ('last_name', 'first_name', 'role'),
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'training_group',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('ID50', 'Indoor swimming track 50m'), ('OD50', 'Outdoor swimming track 50m'), ('ID25', 'Indoor swimming track 25m'), ('OD25', 'Outdoor swimming track 25m'), ('ATID', 'Indoor athletic track'), ('ATOD', 'Outdoor athletic track'), ('OTH', 'Other')], max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=5)),
                ('street_address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.city')),
            ],
            options={
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attended', models.BooleanField(default=True)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.person')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('FA', 'First Aid'), ('RE', 'Rescue ability'), ('LI', 'Lifeguard'), ('CL', 'C-Training license'), ('BL', 'B-Training license'), ('AL', 'A-Training license')], max_length=2)),
                ('date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.person')),
            ],
            options={
                'db_table': 'accreditation',
            },
        ),
        migrations.CreateModel(
            name='TrainingGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('swimmer', 'Swimmer'), ('trainer', 'Trainer'), ('manager', 'Manager')], default='swimmer', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.person')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.traininggroup')),
            ],
            options={
                'db_table': 'training_group_membership',
                'unique_together': {('training_group', 'person')},
            },
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='members',
            field=models.ManyToManyField(related_name='group', through='swimpro.TrainingGroupMembership', to='swimpro.person'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency_days', models.IntegerField(default=7)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.traininggroup')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='swimpro.facility')),
            ],
            options={
                'db_table': 'training_plan',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text="e.g., 'School Holiday', 'Coach Sick'", max_length=200)),
                ('exception_type', models.CharField(choices=[('SKIP', 'Holiday / Cancelled'), ('OVERRIDE', 'Time Change')], max_length=10)),
                ('start_date', models.DateField(help_text='First affected date')),
                ('end_date', models.DateField(blank=True, help_text='Last affected date (leave empty for single-day)', null=True)),
                ('new_start_time', models.DateTimeField(blank=True, null=True)),
                ('new_duration', models.IntegerField(blank=True, null=True)),
                ('plans', models.ManyToManyField(help_text='Select all training plans affected by this exception.', related_name='exceptions', to='swimpro.trainingplan')),
            ],
            options={
                'verbose_name_plural': 'Plan Exceptions',
                'db_table': 'plan_exception',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, through='swimpro.Attendance', to='swimpro.person')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='swimpro.trainingplan')),
            ],
            options={
                'db_table': 'training_session',
                'ordering': ['-session_date'],
                'unique_together': {('plan', 'session_date')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.trainingsession'),
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('self', 'Self'), ('child', 'Child'), ('parent', 'Parent')], default='self', max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimpro.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_person',
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='person', through='swimpro.UserPerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'swimmer')},
        ),
    ]
